CIRCLE_BUILD_NUM ?= 1

containerbin:
	export PKG_CONFIG_PATH=$(GOPATH)/src/github.com/xtraclabs/cqrs-sample-pub/pkgconfig/
	go build -o -ldflags "-s -X github.com/xtracdev/es-atom-replicator/health.Version=$(CIRCLE_BUILD_NUM)" esatomreplicator